"""Write Cypher templates for Report + Message persistence."""

REPORT_UPSERT = (
    "MERGE (r:Report {id: $report_id}) "
    "ON CREATE SET r.created_at = datetime($now) "
    "SET "
    "  r.paragraph_num = $paragraph_num, "
    "  r.stamp = $stamp, "
    "  r.title = $title, "
    "  r.status = $status, "
    "  r.confidence = $confidence, "
    "  r.location = $location, "
    "  r.coords = $coords, "
    "  r.findings = $findings, "
    "  r.metrics_json = $metrics_json, "
    "  r.context = $context, "
    "  r.body_title = $body_title, "
    "  r.body_paragraphs = $body_paragraphs, "
    "  r.margin_json = $margin_json, "
    "  r.sources = $sources, "
    "  r.updated_at = datetime($now) "
    "RETURN "
    "  r.id AS id, "
    "  coalesce(r.paragraph_num, 0) AS paragraph_num, "
    "  coalesce(r.stamp, '') AS stamp, "
    "  coalesce(r.title, '') AS title, "
    "  coalesce(r.status, 'Draft') AS status, "
    "  coalesce(r.confidence, 0.0) AS confidence, "
    "  coalesce(r.location, '') AS location, "
    "  coalesce(r.coords, '') AS coords, "
    "  coalesce(r.findings, []) AS findings, "
    "  coalesce(r.metrics_json, '[]') AS metrics_json, "
    "  coalesce(r.context, '') AS context, "
    "  coalesce(r.body_title, '') AS body_title, "
    "  coalesce(r.body_paragraphs, []) AS body_paragraphs, "
    "  coalesce(r.margin_json, '[]') AS margin_json, "
    "  coalesce(r.sources, []) AS sources, "
    "  toString(r.created_at) AS created_at, "
    "  toString(r.updated_at) AS updated_at"
)

REPORT_DELETE = "MATCH (r:Report {id: $report_id}) DETACH DELETE r"

REPORT_APPEND_MESSAGE = (
    "MATCH (r:Report {id: $report_id}) "
    "MERGE (m:Message {id: $message_id}) "
    "ON CREATE SET m.created_at = datetime($now) "
    "SET "
    "  m.role = $role, "
    "  m.text = $text, "
    "  m.ts = datetime($ts), "
    "  m.refs = $refs, "
    "  m.updated_at = datetime($now) "
    "MERGE (r)-[rel:HAS_MESSAGE]->(m) "
    "SET rel.ordering = $ordering "
    "RETURN "
    "  m.id AS id, "
    "  coalesce(m.role, 'system') AS role, "
    "  coalesce(m.text, '') AS text, "
    "  toString(m.ts) AS ts, "
    "  coalesce(m.refs, []) AS refs, "
    "  coalesce(rel.ordering, 0) AS ordering"
)
